image: docker:latest

services:
  - docker:dind
  
stages:
  - build_image

before_script:
  - export REG_PREFIX="${CI_REGISTRY}/${CI_PROJECT_PATH}"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - export SERVICE_NAME="httpservice"

build-httpservice:
  stage: build_image
  script:
     - export SERVICE_NAME="$SERVICE_NAME"
     - export IMAGE_NAME="${REG_PREFIX}/${SERVICE_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_REF_SLUG}"
     - export IMAGE_NAME_LATEST="${REG_PREFIX}/${SERVICE_NAME}/${CI_COMMIT_REF_SLUG}:latest"
     - docker build --pull -t "${IMAGE_NAME}" -t "${IMAGE_NAME_LATEST}" .
     - docker push "${IMAGE_NAME}"
     - docker push "${IMAGE_NAME_LATEST}"
  only:
    refs:
      - dev