apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "httpservice.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "httpservice.labels" . | nindent 4 }}
data:
  myValue: {{ .Values.configmapvalue }}